docker image test

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,26 +1,66 @@
 pipeline {
     agent any
 
+    environment {
+        DOCKER_REGISTRY = 'registry.spring.com'
+        DOCKER_IMAGE = 'docker-spring'
+        DOCKER_TAG = 'latest'
+    }
+
     stages {
-        stage('Check Docker Version') {
+        stage('Build Docker Image') {
             steps {
-                echo 'Checking Docker version...'
-                sh '''
-                if command -v docker > /dev/null 2>&1; then
-                    echo "Docker is installed."
-                    docker --version
-                else
-                    echo "Docker is NOT installed."
-                    exit 1
-                fi
+                echo '''
+                ------------------------
+                Building Docker Image..
                 '''
+                sh ```
+                    docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG .
+                ```
             }
         }
 
-        stage('build') {
+        stage('Push Docker Image to Registry') {
             steps {
-                sh 'chmod +x ./gradlew'
-                sh './gradlew clean build'
+                echo '''
+                -------------------------
+                Push Docker Image to Registry
+                '''
+                withCredentials([usernamePassword(
+                    credentialsId: 'private-docker-registry',
+                    usernameVariable: 'DOCKER_USERNAME',
+                    passwordVariable: 'DOCKER_PASSWORD'
+                )]) {
+                    sh ```
+                        docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+                        docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG
+                    ```
+                }
+            }
+        }
+
+        stage('Verify Docker Image in Registry') {
+            steps {
+                echo '''
+                -------------------------
+                Verifying Docker Image in Registry...
+                '''
+                withCredentials([usernamePassword(
+                    credentialsId: 'private-docker-registry',
+                    usernameVariable: 'DOCKER_USERNAME',
+                    passwordVariable: 'DOCKER_PASSWORD'
+                )]) {
+                    sh ```
+                        docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+
+                        if docker manifest inspect $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG > /dev/null 2>&1; then
+                            echo "Docker image $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG exists in the registry."
+                        else
+                            echo "ERROR: Docker image $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG not found in the registry!"
+                            exit 1
+                        fi
+                    ```
+                }
             }
         }
     }
